# Generated by Django 3.1.4 on 2021-03-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurevalidator',
            name='feature_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specs.categoryfeature', verbose_name='Ключ характеристики'),
        ),
        migrations.AlterField(
            model_name='productfeatures',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specs.categoryfeature', verbose_name='Характеристика'),
        ),
    ]
