# Generated by Django 3.1.4 on 2021-03-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210320_2126'),
        ('specs', '0002_auto_20210320_2126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductFeatures',
            new_name='ProductFeature',
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='feature_name',
            field=models.CharField(max_length=50, verbose_name='Имя ключа для категории'),
        ),
        migrations.AlterField(
            model_name='featurevalidator',
            name='valid_feature_value',
            field=models.CharField(max_length=100, verbose_name='Валидное значение'),
        ),
    ]
