# Generated by Django 3.1.4 on 2021-03-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0002_auto_20210320_2126'),
        ('mainapp', '0003_auto_20210315_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeaturesvalidators',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productfeaturesvalidators',
            name='feature',
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features_for_product', to='specs.ProductFeatures'),
        ),
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
        migrations.DeleteModel(
            name='ProductFeaturesValidators',
        ),
    ]
